#include "cc.h"

char map[256];
static struct init map_init[] = {
    '\t',  BLANK,       0,
    '\n',  NEWLINE,     0,
    '\v',  BLANK,       0,
    '\f',  BLANK,       0,
    '\r',  BLANK,       0,
    ' ',   BLANK,       0,
    '0',   DIGIT,       0,
    '1',   DIGIT,       0,
    '2',   DIGIT,       0,
    '3',   DIGIT,       0,
    '4',   DIGIT,       0,
    '5',   DIGIT,       0,
    '6',   DIGIT,       0,
    '7',   DIGIT,       0,
    '8',   DIGIT,       0,
    '9',   DIGIT,       0,
    '_',   LETTER,      0,
    'A',   LETTER|HEX,  0,  'a',   LETTER|HEX,  0,
    'B',   LETTER|HEX,  0,  'b',   LETTER|HEX,  0,
    'C',   LETTER|HEX,  0,  'c',   LETTER|HEX,  0,
    'D',   LETTER|HEX,  0,  'd',   LETTER|HEX,  0,
    'E',   LETTER|HEX,  0,  'e',   LETTER|HEX,  0,
    'F',   LETTER|HEX,  0,  'f',   LETTER|HEX,  0,
    'G',   LETTER,      0,  'g',   LETTER,      0,
    'H',   LETTER,      0,  'h',   LETTER,      0,
    'I',   LETTER,      0,  'i',   LETTER,      0,
    'J',   LETTER,      0,  'j',   LETTER,      0,
    'K',   LETTER,      0,  'k',   LETTER,      0,
    'L',   LETTER,      0,  'l',   LETTER,      0,
    'M',   LETTER,      0,  'm',   LETTER,      0,
    'N',   LETTER,      0,  'n',   LETTER,      0,
    'O',   LETTER,      0,  'o',   LETTER,      0,
    'P',   LETTER,      0,  'p',   LETTER,      0,
    'Q',   LETTER,      0,  'q',   LETTER,      0,
    'R',   LETTER,      0,  'r',   LETTER,      0,
    'S',   LETTER,      0,  's',   LETTER,      0,
    'T',   LETTER,      0,  't',   LETTER,      0,
    'U',   LETTER,      0,  'u',   LETTER,      0,
    'V',   LETTER,      0,  'v',   LETTER,      0,
    'W',   LETTER,      0,  'w',   LETTER,      0,
    'X',   LETTER,      0,  'x',   LETTER,      0,
    'Y',   LETTER,      0,  'y',   LETTER,      0,
    'Z',   LETTER,      0,  'z',   LETTER,      0,
    -1, 0, 0
};

int kinds[NTOKEN];
static struct init kinds_init[] = {
    TOK_AUTO,        TOK_STATIC,  0,
    TOK_EXTERN,      TOK_STATIC,  0,
    TOK_REGISTER,    TOK_STATIC,  0,
    TOK_STATIC,      TOK_STATIC,  0,
    TOK_TYPEDEF,     TOK_STATIC,  0,
    TOK_BREAK,       TOK_IF,      0,
    TOK_CASE,        TOK_IF,      0,
    TOK_CONTINUE,    TOK_IF,      0,
    TOK_DEFAULT,     TOK_IF,      0,
    TOK_DO,          TOK_IF,      0,
    TOK_ELSE,        TOK_IF,      0,
    TOK_FOR,         TOK_IF,      0,
    TOK_GOTO,        TOK_IF,      0,
    TOK_IF,          TOK_IF,      0,
    TOK_RETURN,      TOK_IF,      0,
    TOK_SWITCH,      TOK_IF,      0,
    TOK_WHILE,       TOK_IF,      0,
    ';',             TOK_IF,      0,
    '{',             TOK_IF,      0,
    TOK_SIZEOF,      TOK_NAME,    0,
    '!',             TOK_NAME,    0,
    '&',             TOK_NAME,    0,
    '(',             TOK_NAME,    0,
    '*',             TOK_NAME,    0,
    '+',             TOK_NAME,    0,
    '-',             TOK_NAME,    0,
    TOK_INCR,        TOK_NAME,    0,
    TOK_DECR,        TOK_NAME,    0,
    TOK_ICON,        TOK_NAME,    0,
    TOK_FCON,        TOK_NAME,    0,
    TOK_SCON,        TOK_NAME,    0,
    TOK_WSCON,       TOK_NAME,    0,
    TOK_NAME,        TOK_NAME,    0,
    TOK_PP_NUMBER,   TOK_NAME,    0,
    TOK_PP_CHAR,     TOK_NAME,    0,
    TOK_PP_WCHAR,    TOK_NAME,    0,
    '~',             TOK_NAME,    0,
    TOK_VOID,        TOK_INT,     0,
    TOK_BOOL,        TOK_INT,     0,
    TOK_CHAR,        TOK_INT,     0,
    TOK_SHORT,       TOK_INT,     0,
    TOK_ENUM,        TOK_INT,     0,
    TOK_SIGNED,      TOK_INT,     0,
    TOK_INT,         TOK_INT,     0,
    TOK_UNSIGNED,    TOK_INT,     0,
    TOK_LONG,        TOK_INT,     0,
    TOK_FLOAT,       TOK_INT,     0,
    TOK_DOUBLE,      TOK_INT,     0,
    TOK_STRUCT,      TOK_INT,     0,
    TOK_UNION,       TOK_INT,     0,
    TOK_INLINE,      TOK_INT,     0,
    TOK_CONST,       TOK_CONST,   0,
    TOK_RESTRICT,    TOK_CONST,   0,
    TOK_VOLATILE,    TOK_CONST,   0,
    '=',             '=',         0,
    TOK_MULEQ,       '=',         0,
    TOK_ADDEQ,       '=',         0,
    TOK_SUBEQ,       '=',         0,
    TOK_DIVEQ,       '=',         0,
    TOK_MODEQ,       '=',         0,
    TOK_XOREQ,       '=',         0,
    TOK_ANDEQ,       '=',         0,
    TOK_OREQ,        '=',         0,
    TOK_SHLEQ,       '=',         0,
    TOK_SHREQ,       '=',         0,
    -1, 0, 0
};

char precs[NTOKEN];
static struct init precs_init[] = {
    '%',         PREC_MUL,     0,
    '*',         PREC_MUL,     0,
    '/',         PREC_MUL,     0,
    '+',         PREC_ADD,     0,
    '-',         PREC_ADD,     0,
    TOK_SHL,     PREC_SHIFT,   0,
    TOK_SHR,     PREC_SHIFT,   0,
    '<',         PREC_REL,     0,
    '>',         PREC_REL,     0,
    TOK_GEQ,     PREC_REL,     0,
    TOK_LEQ,     PREC_REL,     0,
    TOK_EQ,      PREC_EQ,      0,
    TOK_NEQ,     PREC_EQ,      0,
    '&',         PREC_AND,     0,
    '^',         PREC_XOR,     0,
    '|',         PREC_OR,      0,
    TOK_ANDAND,  PREC_ANDAND,  0,
    TOK_OROR,    PREC_OROR,    0,
    -1, 0, 0
};

const char *lexmes[NTOKEN];
static struct init lexmes_init[] = {
    TOK_XXX,             0,  "<nil>",
    TOK_AUTO,            0,  "auto",
    TOK_EXTERN,          0,  "extern",
    TOK_REGISTER,        0,  "register",
    TOK_STATIC,          0,  "static",
    TOK_TYPEDEF,         0,  "typedef",
    TOK_BREAK,           0,  "break",
    TOK_CASE,            0,  "case",
    TOK_CONTINUE,        0,  "continue",
    TOK_DEFAULT,         0,  "default",
    TOK_DO,              0,  "do",
    TOK_ELSE,            0,  "else",
    TOK_FOR,             0,  "for",
    TOK_GOTO,            0,  "goto",
    TOK_IF,              0,  "if",
    TOK_RETURN,          0,  "return",
    TOK_SWITCH,          0,  "switch",
    TOK_WHILE,           0,  "while",
    TOK_SIZEOF,          0,  "sizeof",
    TOK_VOID,            0,  "void",
    TOK_BOOL,            0,  "_Bool",
    TOK_CHAR,            0,  "char",
    TOK_SHORT,           0,  "short",
    TOK_ENUM,            0,  "enum",
    TOK_SIGNED,          0,  "signed",
    TOK_INT,             0,  "int",
    TOK_UNSIGNED,        0,  "unsigned",
    TOK_LONG,            0,  "long",
    TOK_FLOAT,           0,  "float",
    TOK_DOUBLE,          0,  "double",
    TOK_STRUCT,          0,  "struct",
    TOK_UNION,           0,  "union",
    TOK_INLINE,          0,  "inline",
    TOK_CONST,           0,  "const",
    TOK_VOLATILE,        0,  "volatile",
    TOK_RESTRICT,        0,  "restrict",
    TOK_MULEQ,           0,  "*=",
    TOK_ADDEQ,           0,  "+=",
    TOK_SUBEQ,           0,  "-=",
    TOK_DIVEQ,           0,  "/=",
    TOK_MODEQ,           0,  "%=",
    TOK_XOREQ,           0,  "^=",
    TOK_ANDEQ,           0,  "&=",
    TOK_OREQ,            0,  "|=",
    TOK_SHLEQ,           0,  "<<=",
    TOK_SHREQ,           0,  ">>=",
    TOK_SHL,             0,  "<<",
    TOK_SHR,             0,  ">>",
    TOK_GEQ,             0,  ">=",
    TOK_LEQ,             0,  "<=",
    TOK_EQ,              0,  "==",
    TOK_NEQ,             0,  "!=",
    TOK_INCR,            0,  "++",
    TOK_DECR,            0,  "--",
    TOK_DEREF,           0,  "->",
    TOK_ANDAND,          0,  "&&",
    TOK_OROR,            0,  "||",
    TOK_ELLIPSIS,        0,  "...",
    TOK_ICON,            0,  "ICON",
    TOK_FCON,            0,  "FCON",
    TOK_SCON,            0,  "SCON",
    TOK_WSCON,           0,  "WSCON",
    TOK_NAME,            0,  "identifier",
    TOK_INVALID,         0,  "INVALID",
    TOK_PASTE,           0,  "##",
    TOK_PP_NUMBER,       0,  "PP_NUMBER",
    TOK_PP_CHAR,         0,  "PP_CHAR",
    TOK_PP_WCHAR,        0,  "PP_WCHAR",
    TOK_PP_HEADER_NAME,  0,  "PP_HEADER_NAME",
    TOK_PP_MACRO_ARG,    0,  "PP_MACRO_ARG",
    TOK_EOF,             0,  "EOF",
    '!',                 0,  "!",
    '#',                 0,  "#",
    '$',                 0,  "$",
    '%',                 0,  "%",
    '&',                 0,  "&",
    '(',                 0,  "(",
    ')',                 0,  ")",
    '*',                 0,  "*",
    '+',                 0,  "+",
    ',',                 0,  ",",
    '-',                 0,  "-",
    '.',                 0,  ".",
    '/',                 0,  "/",
    ':',                 0,  ":",
    ';',                 0,  ";",
    '<',                 0,  "<",
    '=',                 0,  "=",
    '>',                 0,  ">",
    '?',                 0,  "?",
    '@',                 0,  "@",
    '[',                 0,  "[",
    ']',                 0,  "]",
    '^',                 0,  "^",
    '{',                 0,  "{",
    '|',                 0,  "|",
    '}',                 0,  "}",
    '~',                 0,  "~",
    -1, 0, 0
};

static struct init keyword_init[] = {
    TOK_AUTO,        0,    0,
    TOK_BREAK,       0,    0,
    TOK_CASE,        0,    0,
    TOK_CHAR,        0,    0,
    TOK_CONST,       0,    0,
    TOK_CONST,       0,    "__const",
    TOK_CONTINUE,    0,    0,
    TOK_DEFAULT,     0,    0,
    TOK_DO,          0,    0,
    TOK_DOUBLE,      0,    0,
    TOK_ELSE,        0,    0,
    TOK_ENUM,        0,    0,
    TOK_EXTERN,      0,    0,
    TOK_FLOAT,       0,    0,
    TOK_FOR,         0,    0,
    TOK_GOTO,        0,    0,
    TOK_IF,          0,    0,
    TOK_INLINE,      0,    0,
    TOK_INLINE,      0,    "__inline",
    TOK_INLINE,      0,    "__inline__",
    TOK_INT,         0,    0,
    TOK_LONG,        0,    0,
    TOK_REGISTER,    0,    0,
    TOK_RESTRICT,    0,    0,
    TOK_RESTRICT,    0,    "__restrict",
    TOK_RESTRICT,    0,    "__restrict__",
    TOK_RETURN,      0,    0,
    TOK_SHORT,       0,    0,
    TOK_SIGNED,      0,    0,
    TOK_SIGNED,      0,    "__signed",
    TOK_SIGNED,      0,    "__signed__",
    TOK_SIZEOF,      0,    0,
    TOK_STATIC,      0,    0,
    TOK_STRUCT,      0,    0,
    TOK_SWITCH,      0,    0,
    TOK_TYPEDEF,     0,    0,
    TOK_UNION,       0,    0,
    TOK_UNSIGNED,    0,    0,
    TOK_VOID,        0,    0,
    TOK_VOLATILE,    0,    0,
    TOK_VOLATILE,    0,    "__volatile",
    TOK_VOLATILE,    0,    "__volatile__",
    TOK_WHILE,       0,    0,
    TOK_BOOL,        0,    0,
    -1, 0, 0
};

static struct init builtins_init[] = {
    BUILTIN_FUNC,       0,  "__func__",
    BUILTIN_VA_START,   0,  "__builtin_va_start",
    BUILTIN_VA_ARG,     0,  "__builtin_va_arg",
    BUILTIN_VA_COPY,    0,  "__builtin_va_copy",
    BUILTIN_VA_END,     0,  "__builtin_va_end",
    BUILTIN_VA_LIST,    0,  "__builtin_va_list",
    -1, 0, 0
};

int bops[NTOKEN];
static struct init bops_init[] = {
    '%',        OMOD,      0,
    '&',        OAND,      0,
    '*',        OMUL,      0,
    '+',        OADD,      0,
    '-',        OSUB,      0,
    '/',        ODIV,      0,
    TOK_MULEQ,  OASMUL,    0,
    TOK_ADDEQ,  OASADD,    0,
    TOK_SUBEQ,  OASSUB,    0,
    TOK_DIVEQ,  OASDIV,    0,
    TOK_MODEQ,  OASMOD,    0,
    '<',        OLT,       0,
    '=',        OAS,       0,
    '>',        OGT,       0,
    TOK_XOREQ,  OASXOR,    0,
    TOK_ANDEQ,  OASAND,    0,
    TOK_OREQ,   OASOR,     0,
    TOK_SHLEQ,  OASSHL,    0,
    TOK_SHREQ,  OASSHR,    0,
    TOK_SHL,    OSHL,      0,
    TOK_SHR,    OSHR,      0,
    TOK_GEQ,    OGE,       0,
    TOK_LEQ,    OLE,       0,
    TOK_EQ,     OEQ,       0,
    TOK_NEQ,    ONE,       0,
    TOK_ANDAND, OANDAND,   0,
    TOK_OROR,   OOROR,     0,
    '^',        OXOR,      0,
    '|',        OOR,       0,
    -1, 0, 0,
};

int uops[NTOKEN];
static struct init uops_init[] = {
    TOK_INCR,   OPREINC,   0,
    TOK_DECR,   OPREDEC,   0,
    '+',        OPOS,      0,
    '-',        ONEG,      0,
    '~',        OCOM,      0,
    '!',        ONOT,      0,
    '&',        OADDR,     0,
    '*',        OINDIR,    0,
    TOK_SIZEOF, OSIZEOF,   0,
    -1, 0, 0
};

const char *tnames[NALLTYPE];
static struct init tnames_init[] = {
    TXXX,         0,  "XXX",
    TBOOL,        0,  "BOOL",
    TCHAR,        0,  "CHAR", 
    TUCHAR,       0,  "UCHAR",
    TSHORT,       0,  "SHORT",
    TUSHORT,      0,  "USHORT",
    TINT,         0,  "INT",
    TUINT,        0,  "UINT",
    TLONG,        0,  "LONG",
    TULONG,       0,  "ULONG",
    TLLONG,       0,  "LLONG",
    TULLONG,      0,  "ULLONG",
    TFLOAT,       0,  "FLOAT",
    TDOUBLE,      0,  "DOUBLE",
    TVOID,        0,  "VOID",
    TPTR,         0,  "PTR",
    TFUNC,        0,  "FUNC",
    TARRAY,       0,  "ARRAY",
    TSTRUCT,      0,  "STRUCT",
    TUNION,       0,  "UNION",
    TENUM,        0,  "ENUM",
    TCONST,       0,  "CONST",
    TVOLATILE,    0,  "VOLATILE",
    TUNSIGNED,    0,  "UNSIGNED",
    TSIGNED,      0,  "SIGNED",
    TAUTO,        0,  "AUTO",
    TEXTERN,      0,  "EXTERN",
    TSTATIC,      0,  "STATIC",
    TTYPEDEF,     0,  "TYPEDEF",
    TREGISTER,    0,  "REGISTER",
    TTYPENAME,    0,  "TYPENAME",
    -1, 0, 0
};

const char *cnames[NCTYPE];
static struct init cnames_init[] = {
    CXXX,       0,  "XXX",
    CAUTO,      0,  "AUTO",
    CEXTERN,    0,  "EXTERN",
    CSTATIC,    0,  "STATIC",
    CTYPEDEF,   0,  "TYPEDEF",
    CREGISTER,  0,  "REGISTER",
    CGLOBAL,    0,  "GLOBAL",
    CENUM,      0,  "ENUM",
    CPARAM,     0,  "PARAM",
    -1, 0, 0
};

const char *onames[NOTYPE];
static struct init onames_init[] = {
    OXXX,       0,  "XXX",
    OLIST,      0,  "LIST",
    OCOMMA,     0,  "COMMA",
    OAS,        0,  "AS",
    OASI,       0,  "ASI",
    OASMUL,     0,  "ASMUL",
    OASUMUL,    0,  "ASUMUL",
    OASADD,     0,  "ASADD",
    OASSUB,     0,  "ASSUB",
    OASDIV,     0,  "ASDIV",
    OASUDIV,    0,  "ASUDIV",
    OASMOD,     0,  "ASMOD",
    OASUMOD,    0,  "ASUMOD",
    OASXOR,     0,  "ASXOR",
    OASAND,     0,  "ASAND",
    OASOR,      0,  "ASOR",
    OASSHL,     0,  "ASSHL",
    OASSHR,     0,  "ASSHR",
    OASUSHR,    0,  "ASUSHR",
    OCOND,      0,  "COND",
    OADD,       0,  "ADD",
    OSUB,       0,  "SUB",
    OMUL,       0,  "MUL",
    OUMUL,      0,  "UMUL",
    ODIV,       0,  "DIV",
    OUDIV,      0,  "UDIV",
    OMOD,       0,  "MOD",
    OUMOD,      0,  "UMOD",
    OAND,       0,  "AND",
    OOR,        0,  "OR",
    OSHL,       0,  "SHL",
    OSHR,       0,  "SHR",
    OUSHR,      0,  "USHR",
    OXOR,       0,  "XOR",
    OLT,        0,  "LT",
    OLE,        0,  "LE",
    OGT,        0,  "GT",
    OGE,        0,  "GE",
    OEQ,        0,  "EQ",
    ONE,        0,  "NE",
    OANDAND,    0,  "ANDAND",
    OOROR,      0,  "OROR",
    OCAST,      0,  "CAST",
    OPREINC,    0,  "PREINC",
    OPREDEC,    0,  "PREDEC",
    OPOS,       0,  "POS",
    ONEG,       0,  "NEG",
    OCOM,       0,  "COM",
    ONOT,       0,  "NOT",
    OADDR,      0,  "ADDR",
    OINDIR,     0,  "INDIR",
    OSIZEOF,    0,  "SIZEOF",
    OPOSTINC,   0,  "POSTINC",
    OPOSTDEC,   0,  "POSTDEC",
    ODOT,       0,  "DOT",
    OFUNC,      0,  "FUNC",
    ONAME,      0,  "NAME",
    OCONST,     0,  "CONST",
    OSTRING,    0,  "STRING",
    OCOMPOUND,  0,  "COMPOUND",
    OINIT,      0,  "INIT",
    OELEM,      0,  "ELEM",
    OARRAY,     0,  "ARRAY",
    OPROTO,     0,  "PROTO",
    OBIT,       0,  "BIT",
    OZERO,      0,  "ZERO",
    OREGISTER,  0,  "OREGISTER",
    OINDREG,    0,  "OINDREG",
    OIF,        0,  "IF",
    OWHILE,     0,  "WHILE",
    ODOWHILE,   0,  "DOWHILE",
    OFOR,       0,  "FOR",
    OSWITCH,    0,  "SWITCH",
    OCASE,      0,  "CASE",
    OLABEL,     0,  "LABEL",
    OGOTO,      0,  "GOTO",
    OBREAK,     0,  "BREAK",
    OCONTINUE,  0,  "CONTINUE",
    ORETURN,    0,  "RETURN",
    -1, 0, 0
};

void tokens_init(void)
{
    struct init *p;
    struct symbol *sym;

    for (p = map_init; p->code >= 0; p++)
        map[p->code] = p->value;
    for (p = kinds_init; p->code >= 0; p++)
        kinds[p->code] = p->value;
    for (p = precs_init; p->code >= 0; p++)
        precs[p->code] = p->value;
    for (p = lexmes_init; p->code >= 0; p++)
        lexmes[p->code] = p->s;
    for (p = keyword_init; p->code >= 0; p++) {
        sym = lookup(p->s ? p->s : lexmes[p->code], OPT_CREATE);
        sym->keyword_id = p->code;
    }
    for (p = bops_init; p->code >= 0; p++)
        bops[p->code] = p->value;
    for (p = uops_init; p->code >= 0; p++)
        uops[p->code] = p->value;
    for (p = tnames_init; p->code >= 0; p++)
        tnames[p->code] = p->s;
    for (p = cnames_init; p->code >= 0; p++)
        cnames[p->code] = p->s;
    for (p = onames_init; p->code >= 0; p++)
        onames[p->code] = p->s;
    for (p = builtins_init; p->code >= 0; p++)
        if (p->s) {
            sym = lookup(p->s, OPT_CREATE);
            sym->builtin_id = p->code;
        }
}
